# Generated by Django 5.0.2 on 2024-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
